### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by rball11** [rball11/DMIT-2018-Workbook#2]
Create a page that shows our suppliers and the products they offer. I will need to see the information in the following "structure"

- **Supplier**
  - Company Name
  - Contact Name
  - Phone Number
  - **Product Summary**
    - Product Name
    - Category Name
    - Unit Price
    - Quantity/Unit

### Tasks
- [x] Create LINQ Query in LinqPad
- [x] Create classes for the Read Model
- [x] Copy/adapt LinqPad query to BLL method
- [x] Create page with nested repeater
